### ISSUE TITLE
Helm chart version 1.8.0 does not exist

### ISSUE THREAD

**Issue by calvinbui** [aws-observability/helm-charts#60]
The latest version is 1.7.0 at https://aws-observability.github.io/helm-charts/index.yaml

It appears to be manually executed at https://github.com/aws-observability/helm-charts/actions/workflows/release.yaml by either @movence or @mitali-salvi

**Comment by mitali-salvi** [comment]
Hey @calvinbui, thank you for reporting this issue. Helm Chart version 1.8.0 for ```amazon-cloudwatch-observability``` was released 3 days ago and is available at https://github.com/aws-observability/helm-charts/releases as well.
